### ISSUE TITLE
信息回调中存在内存泄露

### ISSUE THREAD

**Issue by aileshe** [wlgq2/uv-cpp#11]
![image](https://user-images.githubusercontent.com/28887594/76837052-d656f080-686c-11ea-8662-68398b496e5c.png)
![image](https://user-images.githubusercontent.com/28887594/76837159-01d9db00-686d-11ea-99eb-3f965f1ae46c.png)
![image](https://user-images.githubusercontent.com/28887594/76837168-07372580-686d-11ea-8822-b8780264f43e.png)

**Comment by wlgq2** [comment]
直接调用conn->close()不会删除连接池，需要调用TcpServer::closeConnection(conn->Name()) 关闭连接即可。
