### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by AheadSnail** [wlgq2/uv-cpp#12]
EventLoop::~EventLoop()
{
    if (loop_ != uv_default_loop())
    {   
        uv_loop_close(loop_);
		delete loop_;
		delete async_;
    }
}

如果loop不为全局静态的也要释放 async_吧

**Comment by wlgq2** [comment]
不需要，就算写了delete async_ ；实际也不会被调用，因为DeafaultEvent本来就是一个单例，不需要被释放 。

**Comment by AheadSnail** [comment]
你还是不懂我的意思，我说的是如果当前的 EventLoop 如果是new出来的，那这个async_ 就没有释放了

**Comment by wlgq2** [comment]
public:
    enum Mode
    {
        Default,
        New
    };

    EventLoop();
private:
    EventLoop(Mode mode);

EventLoop::EventLoop()
    :EventLoop(EventLoop::Mode::New)
{
}

带模式new EventLoop的函数是私有的，外部new不出Default模式的EventLoop，只能new出新的EventLoop

**Comment by AheadSnail** [comment]
额，好像静态的话，释不释放都没关系了

**Comment by yuzu-ogura** [comment]
```
EventLoop::~EventLoop()
{
    if (loop_ != uv_default_loop())
    {   
        uv_loop_close(loop_);
        delete async_;
        delete loop_;
    }
}
```
@wlgq2 请问为什么要再析构函数里加上这样一个if判断，是有什么特别的作用吗？
