### ISSUE TITLE
TCPServer

### ISSUE THREAD

**Issue by silencelbl** [wlgq2/uv-cpp#14]
请问, uv-pp在TCP服务器下, 怎么开启多线程模式呢?

**Comment by wlgq2** [comment]
如果你说的的多线程是指一个线程accept，然后把connection抛给线程池。那么受限于libuv本身，做不到。因为libuv会强制检测accept的loop和connection的loop是否一直，不一致则异常退出。

但是如果你一定要用多线程，有两个折中方案。
1.开多个server，每个server监听一个端口占一个线程，客户端做负载均衡。
2.后台开线程池处理耗CPU任务，通过uv-cpp提供的async接口与loop线程交互。

**Comment by silencelbl** [comment]
是的, 之前问的多线程模式, 就是一个线程accept，然后把connection抛给线程池.曾用过libev封装.一个线程listen, 多个线程读写.通过async接口和主线程交互. 应该就是你说的第二种模式
