### ISSUE TITLE
TcpConnection::onMessageReceive关于nread小于0的处理

### ISSUE THREAD

**Issue by silencelbl** [wlgq2/uv-cpp#16]
关于TcpConnection::onMessageReceive可读消息回调, 在处理nread < 0 时.对返回值UV_EOF采取的uv_shutdown方式关闭, 为什么不直接用uv_close呢

**Comment by yandaomin** [comment]
shutdown可以指定在某个方向上终止连接，通过指定标志：SHUT_RD, SHUT_WR, SHUT_RDWR。比如指定SHUT_WR后可以继续读数据，但不能写入了。而close是两个方向上终止连接。
close会将描述符的引用计数减一，如果引用计数变为0就关闭描述符，发送FIN。而shutdown不管引用计数，直接发送FIN终止连接。所以在多线程下操作同一个socket描述符下，一个线程调用shutdown会使其他线程无法使用这个描述符，而调用close就不会影响到其他线程。
