### ISSUE TITLE
TcpAccepter::bind绑定失败

### ISSUE THREAD

**Issue by silencelbl** [wlgq2/uv-cpp#17]
在centos7.5下使用uv-cpp, 启动echo_server, 在绑定当前服务器的公网IP时, bind失败, 返回(-99)错误: socket_bind(): unable to bind address [99]. (保证IP,端口无错误), 另外启的一个服务器使用相同的IP,端口可正常绑定.是否是libuv在绑定地址端口的时候只能填写(127.0.0.0.1或0.0.0.0). echo_server在更改IP为0.0.0.0后, 可以正常运行.

**Comment by wlgq2** [comment]
http://docs.libuv.org/en/v1.x/tcp.html?highlight=bind#c.uv_tcp_bind
TcpAccept里面的bind是调用libuv的bind并转发结果。
