### ISSUE TITLE
请问目前支持多播和组播功能吗

### ISSUE THREAD

**Issue by cjl3230** [wlgq2/uv-cpp#19]

**Comment by wlgq2** [comment]
暂不支持，后面考虑。

**Comment by ColdwindY** [comment]
是否增加一个方法
int uv::Udp::set_broadcast(int on) 
{
	return uv_udp_set_broadcast(handle_, on);
}
在send(),前调用一下set_broadcast(1)，就可以进行广播了

**Comment by wlgq2** [comment]
@ColdwindY 我不怎么用UDP，你觉得没问题，可以提交个pr，有时间也可也提交个使用例程。

**Comment by wangwenqiangGitHub** [comment]
想问一下支持udp组播了么
