### ISSUE TITLE
TimerWheel 类的作用

### ISSUE THREAD

**Issue by zhangtaohbwh** [wlgq2/uv-cpp#22]
我看文档里的 TimerWheel 类，说是超时剔除机制，现在有个疑问，就是新连接对象被保存在两个地方了，一个是TcpServer类的connnections_成员中（connnections_中的保存要在客户端主动断开才会被删除），一个是TimerWheel类的wheel_成员中（在指定的超时时间后被删除），超时剔除机制是什么意思呢？是在指定的超时时间后，断开与客户端的连接吗，还是有其它的含义呢？

**Comment by wlgq2** [comment]
你做个测试就明白了。约定时间长度内，如果Server没收到任何一条Tcp消息，就会断开并删除该连接。需要间隔发心跳协议，避免自己被断开删除。

**Comment by zhangtaohbwh** [comment]
我用 echo_server.exe 和 clients.exe做测试，把 TimerWheel中的 timeoutSec_ 成员指定为5，在同一机器上把服务和客户端都启动，但是，过了5秒后，客户端好像都没有自动断开哦，这是什么情况？如果客户端断开了，服务端会检测到断开，并输出一条日志，但是过了5秒并没有输出日志

**Comment by wlgq2** [comment]
不是客户端断开，是服务端主动断开连接。前提是这五秒没有消息通信，你记得注释掉clients代码里面发送消息部分。我测试下是会断开的，服务端不会打日志，但是客户端在5s后会打一个连接被断开的日志。

**Comment by zhangtaohbwh** [comment]
谢谢，知道了，现在正在学习您封装的libuv库uv-cpp
