### ISSUE TITLE
VS2015下使用时编译报错，而且错误很奇怪

### ISSUE THREAD

**Issue by xhqxhq** [wlgq2/uv-cpp#23]
我用VS2015编译uv_cpp为静态库后，在新工程中包含include头文件目录，编译时出现如下错误:
\vs2015\vc\include\initializer_list(15): error C2894: templates cannot be declared to have 'C' lin
\vs2015\vc\include\initializer_list(59): error C2894: templates cannot be declared to have 'C' lin
\vs2015\vc\include\initializer_list(66): error C2894: templates cannot be declared to have 'C' lin
\vs2015\vc\include\xtr1common(20): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(44): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(48): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(55): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(61): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(68): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(76): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(84): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(91): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(98): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(104): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(110): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(117): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(123): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(130): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(138): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(144): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(150): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(156): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(162): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(169): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(176): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(182): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(188): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(194): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(200): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(206): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(212): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(218): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(224): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(230): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(237): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(244): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(249): error C2894: templates cannot be declared to have 'C' linkage
\vs2015\vc\include\xtr1common(255): error C2894: templates cannot be declared to have 'C' linkage
不包含uv_cpp的include文件夹时编译没有问题，百思不得其解

**Comment by wlgq2** [comment]
这个问题，我记得很久之前我也遇到过 ，很奇怪，我注释掉模板后，还提示这个。当时我没排查出来，最后重建工程后，就一切正常了。可能和vs编译器有关系，你试试GCC。如果你能 找到原因，麻烦告知下。

**Comment by wlgq2** [comment]
你试试给 所有的 #include <uv.h>加上 extern C，或者项目宏定义__cplusplus试试。

**Comment by xhqxhq** [comment]
问题找到了，在设置VS工程属性的"Additional Include Directories"包含头文件时,不能包含到include文件夹。
例如，我将uv_pp放在uvWrapper文件夹中，目录如下:
![image](https://user-images.githubusercontent.com/16683388/88869156-a2410280-d244-11ea-8cfa-ae8df66f1c52.png)
应该这样包含头文件编译时才不会报错:
![image](https://user-images.githubusercontent.com/16683388/88869286-f21fc980-d244-11ea-90be-12fedb0075ff.png)
如果包含头文件时包含到include文件夹就会编译报错:"..\uvWrapper\include"
造成原因为知。。。

**Comment by wlgq2** [comment]
问题找到了，因为inclue文件夹包含 Signal.h，应该是这个文件名某个系统文件同名，导致如果把include目录添加到默认目录，某个libuv的模块某include到这个文件。
