### ISSUE TITLE
TcpServer如何退出事件循环并做好收尾工作呢？

### ISSUE THREAD

**Issue by xhqxhq** [wlgq2/uv-cpp#24]
TcpServer如何退出事件循环并做好收尾工作呢？

**Comment by wlgq2** [comment]
因为这个库主要是服务我自己项目。当时没这个需求。这个接口加起来不难，最近疲与找工作，后面会加。

**Comment by wlgq2** [comment]
v1.5.2 引入server退出，详见例程：https://github.com/wlgq2/uv-cpp/tree/master/examples/server_quit
