### ISSUE TITLE
TcpConnection::write函数中似乎有隐藏的内存泄露问题？

### ISSUE THREAD

**Issue by zhangtaohbwh** [wlgq2/uv-cpp#25]
`int TcpConnection::write(const char* buf, ssize_t size, AfterWriteCallback callback)
{
    int rst;
    if (connected_)
    {
        WriteReq* req = new WriteReq;
        req->buf = uv_buf_init(const_cast<char*>(buf), static_cast<unsigned int>(size));
        req->callback = callback;
        auto ptr = handle_.get();
        rst = ::uv_write((uv_write_t*)req, (uv_stream_t*)ptr, &req->buf, 1,
            [](uv_write_t *req, int status)
        {
            WriteReq *wr = (WriteReq*)req;
            if (nullptr != wr->callback)
            {
                struct WriteInfo info;
                info.buf = const_cast<char*>(wr->buf.base);
                info.size = wr->buf.len;
                info.status = status;
                wr->callback(info);
            }
            delete wr;
        });
        if (0 != rst)
        {
            uv::LogWriter::Instance()->error(std::string("write data error:"+std::to_string(rst)));
            if (nullptr != callback)
            {
                struct WriteInfo info = { rst,const_cast<char*>(buf),static_cast<unsigned long>(size) };
                callback(info);
            }
        }
    }
    else
    {
        rst = -1;
        if (nullptr != callback)
        {
            struct WriteInfo info = { WriteInfo::Disconnected,const_cast<char*>(buf),static_cast<unsigned long>(size) };
            callback(info);
        }
    }
    return rst;
}`

上面这段代码中，new了一个 WriteReq 对象 req，如果程序不执行到 delete wr; 语句，那不就有内存泄露呀

**Comment by wlgq2** [comment]
```
void (*uv_write_cb)(uv_write_t* req, int status)
Callback called after data was written on a stream. status will be 0 in case of success, < 0 otherwise.

```
write失败好像确实不会触发回调。

**Comment by zhangtaohbwh** [comment]
哦，好的

**Comment by wlgq2** [comment]
return 返回非零时候，确实不会调用回调。
