### ISSUE TITLE
TcpServer在客户端断开后发送数据崩溃

### ISSUE THREAD

**Issue by xhqxhq** [wlgq2/uv-cpp#26]
刚刚发现一个小问题，客户端和服务端频繁相互发送数据时，TcpClient断开后，TcpConnection被销毁，但是在被销毁之前，在非事件循环线程中通过调用TcpConnection::writeInLoop向事件循环投递一块要发送的数据，由于不在事件循环中，所以这个待发送数据被放入了EventLoop类对象的待发送队列中(async_数据成员):
![image](https://user-images.githubusercontent.com/16683388/89988309-eeaf2800-dcb1-11ea-8a4e-358ce673a01a.png)
但是当这个发送数据的请求被执行时，TcpConnection连接对象已经被销毁，所以在写入数据时会崩溃，问题代码应该在这里:
![image](https://user-images.githubusercontent.com/16683388/89988752-9167a680-dcb2-11ea-8c60-2f82e9b23432.png)
这里将this指针作为lambda表达式的捕获参数，当TcpConnnection对象被释放了之后，this指针指向被释放的内存，所以会造成崩溃，我尝试改成如下方式，用TcpConnection的弱引用来代替this指针，在lambda表达式内部
检测TcpConnection连接对象是否有效：
![image](https://user-images.githubusercontent.com/16683388/89991445-6ed78c80-dcb6-11ea-8273-62cc86705014.png)

**Comment by wlgq2** [comment]
是这样的，如果你有时间可以提交下pr。

**Comment by wlgq2** [comment]
已修复。

**Comment by xhqxhq** [comment]
祝大佬早日找到心仪的工作
