### ISSUE TITLE
packet中size为uint16_t存放数据长度是否太小?

### ISSUE THREAD

**Issue by CrazyWolf2014** [wlgq2/uv-cpp#30]
packet中size为uint16_t存放数据长度是否太小? 如果传递数据大于0xFFFF不能一次发送完.

**Comment by wlgq2** [comment]
一个包六万个字节够了吧，TCP自己最大一帧才发送 1500个字节。

**Comment by CrazyWolf2014** [comment]
> 一个包六万个字节够了吧，TCP自己最大一帧才发送 1500个字节。

可能我没有描述清楚，我想说的是我想单次发送超过0xFFFF个字节的数据的时候（比如发送稍微大点的文件）。这个时候需要自己额外再分包处理一次。
