### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by zhangtaohbwh** [wlgq2/uv-cpp#32]
我在新建的空项目中，把 uv 中的代码拷贝进来，编译报错，报错信息如下，使用的IDE是vs2019
![image](https://user-images.githubusercontent.com/26736905/101643879-8a3d8300-3a6f-11eb-8403-0f47cd478bfc.png)

**Comment by wlgq2** [comment]
https://github.com/wlgq2/uv-cpp/issues/23

**Comment by wlgq2** [comment]
排查发现Signal.h可能何某个系统文件重名，所以把uv/include添加到寻找目录就会出这个问题。
下一版本解决。
