### ISSUE TITLE
TimerWheel 类的是否会将没有超时连接删除

### ISSUE THREAD

**Issue by x200502126115** [wlgq2/uv-cpp#33]
void uv::TcpServer::onAccept(EventLoop * loop, UVTcpPtr client)
{
    string key;
    SocketAddr::AddrToStr(client.get(), key, ipv_);

    uv::LogWriter::Instance()->debug("new connect  " + key);
    shared_ptr<TcpConnection> connection(new TcpConnection(loop, key, client));
    if (connection)
    {
        connection->setMessageCallback(std::bind(&TcpServer::onMessage, this, placeholders::_1, placeholders::_2, placeholders::_3));
        connection->setConnectCloseCallback(std::bind(&TcpServer::closeConnection, this, placeholders::_1));
        addConnnection(key, connection);
        if (timerWheel_.getTimeout() > 0)
        {
            auto wrapper = std::make_shared<ConnectionWrapper>(connection);
            connection->setWrapper(wrapper);
            timerWheel_.insert(wrapper);
        }
        if (onNewConnectCallback_)
            onNewConnectCallback_(connection);
    }
    else
    {
        uv::LogWriter::Instance()->error("create connection fail. :" + key);
    }
}

新连接过来后，会将对应连接插入 std::vector<std::set<std::shared_ptr<Type>>> wheel_;

回调过程中会周期的增加index_
template<typename Type>
inline void TimerWheel<Type>::wheelCallback()
{
    if (!timeoutSec_)
        return;
    if (++index_ == timeoutSec_)
    {
        index_ = 0;
    }
    wheel_[index_].clear();
}
}

若有多个用户情况下，必然会有多个连接公用一共index_，clear过程是否会导致删除多个连接的可能性。

**Comment by wlgq2** [comment]
不会，clear并不会删除连接对象，所有连接对象副本都被clear才会才会删除，只要约定时间内，该连接有消息通信，该连接就会在time_wheel中有多个副本存在。

**Comment by x200502126115** [comment]
非常感谢，是因为这个地方每次都添加了新的副本是吧？
void TcpServer::onMessage(TcpConnectionPtr connection,const char* buf,ssize_t size)
{
    if(onMessageCallback_)
        onMessageCallback_(connection,buf,size);
    if (timerWheel_.getTimeout() > 0)
    {
        timerWheel_.insert(connection->getWrapper());
    }
}

**Comment by yandaomin** [comment]
我有一个问题请教一下，TimerWheel 类的作用是什么？
因为我看在TcpServer中已经存放了TcpConnection的智能指针，这时TcpConnection不会被释放，只有从map中清除才会释放，所以我有些疑惑，为何还需要TimerWheel 以及ConnectionWrapper？
期盼得到 回答 ，谢谢。

**Comment by x200502126115** [comment]
> 我有一个问题请教一下，TimerWheel 类的作用是什么？
> 因为我看在TcpServer中已经存放了TcpConnection的智能指针，这时TcpConnection不会被释放，只有从map中清除才会释放，所以我有些疑惑，为何还需要TimerWheel 以及ConnectionWrapper？
> 期盼得到 回答 ，谢谢。

主要是用来超时处理，如果超过了设定时间，就会被clear掉

**Comment by yandaomin** [comment]
了解了，感谢
















在 2021-01-20 11:41:16，"x200502126115" <notifications@github.com> 写道：

我有一个问题请教一下，TimerWheel 类的作用是什么？
因为我看在TcpServer中已经存放了TcpConnection的智能指针，这时TcpConnection不会被释放，只有从map中清除才会释放，所以我有些疑惑，为何还需要TimerWheel 以及ConnectionWrapper？
期盼得到 回答 ，谢谢。

主要是用来超时处理，如果超过了设定时间，就会被clear掉

**Comment by qq805005062** [comment]
> 不会，clear并不会删除连接对象，所有连接对象副本都被clear才会才会删除，只要约定时间内，该连接有消息通信，该连接就会在time_wheel中有多个副本存在。


一个进程一个Loop，然后网络收到的消息都加入uv_queue_work,在这里执行的，定时器任务有一小部分没有在这个里面执行，这样做可以吗？我的是客户端，排除应用层的奔溃，可能是我对libuv库不够熟悉，使用方法不对，就是偶尔会奔溃，有时候程序运行着，CPu使用率高达100%，我在Gdb调试时也遇到过，所以我Ctrl+c暂停查看堆栈，发现并没有异常，有什么好的建议给我指点下，或者加我的QQ号，帮我看看？非常感谢！！

**Comment by x200502126115** [comment]
@qq805005062  uv_queue_work 加入的任务会在线程池去处理，处理结束后会回到loop主线程处理对应回调函数。不是特别明白你想干什么。

**Comment by qq805005062** [comment]
> @qq805005062 uv_queue_work 加入的任务会在线程池去处理，处理结束后会回到loop主线程处理对应回调函数。不是特别明白你想干什么。

就是让耗时的工作，在子线程里执行啊，主线程只负责调度
