### ISSUE TITLE
centos 7 运行一晚第二天看到崩溃了

### ISSUE THREAD

**Issue by qq805005062** [wlgq2/uv-cpp#43]
Program received signal SIGSEGV, Segmentation fault.
malloc_consolidate (av=av@entry=0x7ffff6f8c760 <main_arena>) at malloc.c:4147
4147		  nextsize = chunksize(nextchunk);
(gdb) bt
#0  malloc_consolidate (av=av@entry=0x7ffff6f8c760 <main_arena>) at malloc.c:4147
#1  0x00007ffff6c4620e in _int_free (av=0x7ffff6f8c760 <main_arena>, p=0x7a92e0, have_lock=0) at malloc.c:4053
#2  0x00000000004e23fa in _M_dispose (__a=..., this=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/ext/atomicity.h:82
#3  _M_dispose (__a=..., this=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3250
#4  ~basic_string (this=0x7ba410, __in_chrg=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3640
#5  uv::TcpConnection::~TcpConnection (this=0x7ba3d0, __in_chrg=<optimized out>) at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/uv-cpp1.5.4/uv/TcpConnection.cpp:44
#6  0x00000000004e1b3a in _M_release (this=0x7ba3c0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/ext/atomicity.h:69
#7  _M_release (this=0x7ba3c0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:148
#8  ~__shared_count (this=<optimized out>, __in_chrg=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:728
#9  ~__shared_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:1167
#10 operator= (__r=<optimized out>, this=0x7a8920) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:1263
#11 operator= (__r=<optimized out>, this=0x7a8920) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr.h:335
#12 uv::TcpClient::onConnect(bool) () at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/uv-cpp1.5.4/uv/TcpClient.cpp:112
#13 0x00000000004e1c0a in operator() (__closure=0x0, req=<optimized out>, status=<optimized out>) at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/uv-cpp1.5.4/uv/TcpClient.cpp:101
#14 uv::TcpClient::connect(uv::SocketAddr&)::{lambda(uv_connect_s*, int)#1}::_FUN(uv_connect_s*, int) () at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/uv-cpp1.5.4/uv/TcpClient.cpp:102
#15 0x00000000004f6d0a in uv__stream_connect (stream=0x7baf00) at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/libuv-1.42.0/src/unix/stream.c:1391
#16 0x00000000004f6a48 in uv__stream_io (loop=0x7a7010, w=0x7baf88, events=4) at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/libuv-1.42.0/src/unix/stream.c:1308
#17 0x0000000000500009 in uv__io_poll (loop=0x7a7010, timeout=312) at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/libuv-1.42.0/src/unix/epoll.c:374
#18 0x00000000004ec791 in uv_run (loop=0x7a7010, mode=UV_RUN_DEFAULT) at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/libuv-1.42.0/src/unix/core.c:389
#19 0x00000000004df8f0 in uv::EventLoop::run (this=0x7a76b0) at /mnt/hgfs/workspace/gitee/metel_sdp/client/third_party/uv-cpp1.5.4/uv/EventLoop.cpp:67
#20 0x0000000000448218 in main (argc=1, argv=0x7fffffffe628) at /mnt/hgfs/workspace/gitee/metel_sdp/client/sdp/app/main.cpp:101
(gdb) info thread
  Id   Target Id         Frame 
  6    Thread 0x7ffff488f700 (LWP 3189688) "sdp" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7ffff5090700 (LWP 3189687) "sdp" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7ffff5891700 (LWP 3189686) "sdp" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7ffff6092700 (LWP 3189685) "sdp" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7ffff6893700 (LWP 3189682) "sdp" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
* 1    Thread 0x7ffff7fe6780 (LWP 3189678) "sdp" malloc_consolidate (av=av@entry=0x7ffff6f8c760 <main_arena>) at malloc.c:4147
(gdb) 
网络先断开后重连出现了一次上面的这个问题 uv-cpp1.5.4/uv/TcpClient.cpp:112
![1636078950(1)](https://user-images.githubusercontent.com/22863573/140447714-b5bdfe4d-0e48-4be0-8164-726d7b337302.png)
uv-cpp1.5.4/uv/TcpConnection.cpp:44
![1636078990(1)](https://user-images.githubusercontent.com/22863573/140447760-2491cdfe-cda4-41d0-be0c-18dd0634b423.png)

**Comment by wlgq2** [comment]
首先我不能帮你排查业务逻辑且也做不到，更没有义务。
其次崩溃在库里并不能说明是库的bug，简单例子，你多线程写std容器肯定会崩，但不是容器的bug。
最后，如果崩溃能复现（比如一晚上一次），是容易排查到原因的。uv-cpp代码并不复杂，如果真是库问题，可以麻烦提交个pr，谢谢。

**Comment by qq805005062** [comment]
> 首先我不能帮你排查业务逻辑且也做不到，更没有义务。 其次崩溃在库里并不能说明是库的bug，简单例子，你多线程写std容器肯定会崩，但不是容器的bug。 最后，如果崩溃能复现（比如一晚上一次），是容易排查到原因的。uv-cpp代码并不复杂，如果真是库问题，可以麻烦提交个pr，谢谢。

一个进程一个Loop，然后网络收到的消息都加入uv_queue_work,在这里执行的，定时器认为有一小部分没有在这个里面执行，这样做可以吗？有什么建议给我指点下，我这加我的QQ号，帮我看看？
