### ISSUE TITLE
有没有多线程或者线程池的例子，如何开16个线程

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [wlgq2/uv-cpp#49]
看了一下example的，一般是两个线程的例子，如何使用更多线程，可以考虑加EventLoop更多线程的例子么

**Comment by wangwenqiangGitHub** [comment]
> 只有EventLoop和线程有安全性问题。 for(1:16) { 创建一个线程callback，在callback里面new一个everloop。或者run 事先创建的eventloop数组元素 [i] }

感谢，还有一个问题，这个库我在使用的时候，发现cpu占用率很高，如何设置呢，是没有使用对么，我其实只用了runInLoop函数处理另一个线程的数据

**Comment by wlgq2** [comment]
cpu占用高跟这个库本身没啥关系。这里没有消耗CPU的操作，cpu占用取决你runInLoop里面回调的逻辑。你可以试试把相关callback里面代码注释掉。或者看看有啥工具有火焰图。

**Comment by wlgq2** [comment]
所有可能消耗的CPU的操作我都规避了，唯一相对耗点CPU的是从buf读写数据，但是那个也几乎耗费不了多少CPU。

**Comment by wangwenqiangGitHub** [comment]
> cpu占用高跟这个库本身没啥关系。这里没有消耗CPU的操作，cpu占用取决你runInLoop里面回调的逻辑。你可以试试把相关callback里面代码注释掉。或者看看有啥工具有火焰图。
我测试了一下，我在生产数据的线程中处理，和runInLoop把数据接过来处理，cpu占用率前者是10%左右，后者70%， 具体原因我还要排查一下

**Comment by wangwenqiangGitHub** [comment]
> 所有可能消耗的CPU的操作我都规避了，唯一相对耗点CPU的是从buf读写数据，但是那个也几乎耗费不了多少CPU。

找到原因了，是我程序中引用的另一个库，占用cpu比较高，当时测试的时候，漏屏蔽了，也写了测试例子，runInLoop并不会过高，通过线程池也可以测试出来 ，感谢解答
