### ISSUE TITLE
Question：为什么只有TcpServer端才有setTimeout接口，客户端没有相应的setTimeout接口？

### ISSUE THREAD

**Issue by yuzu-ogura** [wlgq2/uv-cpp#50]
您好，想请教一下：
为什么只有TcpServer端才有setTimeout接口，客户端没有相应的setTimeout接口呢？

**Comment by wlgq2** [comment]
这里的逻辑是client发送心跳包，server监测心跳包。这样时间复杂度低点。

**Comment by yuzu-ogura** [comment]
好的，谢谢您的回复
