### ISSUE TITLE
通过来源服务器的链接端口生成字符串来作为连接名称，值得商榷

### ISSUE THREAD

**Issue by hubinix** [wlgq2/uv-cpp#6]
string name;
        SocketAddr::AddrToStr(socket_,name,ipv);

        connection_ = make_shared<TcpConnection>(loop_, name, socket_);
常见做法是用自增数。

**Comment by wlgq2** [comment]
假设来自A客户端连接自增ID为0。B客户端为1，B反复断开重连，服务运行足够久，理论上这个数总会溢出，然后B的ID也会为0。当然，用自增ID前可以检查下是否被使用，但也增加了一点时间复杂度。用IP+端口不存在这个问题，可以保证在 同一时刻永远唯一。
