### ISSUE TITLE
在TcpClient.cpp文件里面 socket_ = new uv_tcp_t();存在内存泄露

### ISSUE THREAD

**Issue by hubinix** [wlgq2/uv-cpp#9]
https://github.com/wlgq2/uv-cpp/blob/master/uv/TcpClient.cpp
update方法存在内存泄露
uv_tcp_t的对象new出来之后，没有对应的delete代码。
 socket_ = new uv_tcp_t();

**Comment by wlgq2** [comment]
是这样的，这个socket_对象被传递到TcpConnection类里面，并在TcpConnection析构函数里面被delete，因为TcpConnection是用shared_ptr保存，所以，新创建TcpConnection时候，这个函数就被析构了。
